name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy files to EC2
        run: |
          echo "$ssh-private-key" > private_key && chmod 600 private_key
          scp -r -o StrictHostKeyChecking=no private_key ec2-user@15.229.117.94:/home/ec2-user/app

      - name: SSH into EC2 and deploy
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@15.229.117.94 << 'EOF'
            cd /home/ec2-user/app
            docker-compose down
            docker-compose up --build -d
          EOF
