name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy files to EC2
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key && chmod 600 private_key
          scp -i private_key -r -o StrictHostKeyChecking=no . ec2-user@15.228.247.16:/home/ec2-user/app

      - name: SSH into EC2 and deploy
        run: |
          ssh -i private_key -o StrictHostKeyChecking=no ec2-user@15.228.247.16 << 'EOF'
            cd /home/ec2-user/app
            docker-compose down
            docker-compose up --build -d
          EOF
